const constantValues  = {
 MONTHLY_INVESTMENT_MIN : 500,
 MONTHLY_INVESTMENT_MAX : 1000000,
 INVESTMENT_PERIOD_MIN : 1,
 INVESTMENT_PERIOD_MAX : 30,
 RATE_OF_RETURN_MIN :1,
 RATE_OF_RETURN_MAX :30,
 RATE_OF_INFLATION_MIN :0,
 RATE_OF_INFLATION_MAX :30,
 MONTHS_IN_A_YEAR:12
}

module.exports = { constantValues }