const constants  = {
 MONTHLYINVESTMENTMIN : 500,
 MONTHLYINVESTMENTMAX : 1000000,
 INVESTMENTPERIODMIN : 1,
 INVESTMENTPERIODMAX : 30,
 RATEOFRETURNMIN :1,
 RATEOFRETURNMAX :30,
 RATEOFINFLATIONMIN :0,
 RATEOFINFLATIONMAX :30,
 MONTHSINAYEAR:12
}

module.exports = { constants };