const MONTHLYINVESTMENTMIN =  500;
const MONTHLYINVESTMENTMAX =  1000000;
const INVESTMENTPERIODMIN =  1;
const INVESTMENTPERIODMAX =  30;
const  RATEOFRETURNMIN = 1;
const  RATEOFRETURNMAX = 30;
const  RATEOFINFLATIONMIN = 0;
const  RATEOFINFLATIONMAX = 30;

module.exports = {
    MONTHLYINVESTMENTMIN,
    MONTHLYINVESTMENTMAX,
    INVESTMENTPERIODMIN,
    INVESTMENTPERIODMAX,
    RATEOFRETURNMIN,
    RATEOFRETURNMAX,
    RATEOFINFLATIONMIN,
    RATEOFINFLATIONMAX
};